# Generated by Django 4.1.7 on 2023-05-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_sectiondb'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiondb',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
