# Generated by Django 4.2.1 on 2023-05-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loandb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Number', models.IntegerField(blank=True, null=True)),
                ('Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Period', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
