# Generated by Django 4.2.1 on 2023-06-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_loandb'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('Firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('Lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('Dob', models.CharField(blank=True, max_length=100, null=True)),
                ('Gender', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Address1', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('No', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Nominee', models.CharField(blank=True, max_length=100, null=True)),
                ('Relation', models.CharField(blank=True, max_length=100, null=True)),
                ('Occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('Iden', models.CharField(blank=True, max_length=100, null=True)),
                ('Idcard', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('Account', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('Sign', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
