# Generated by Django 4.2.1 on 2023-06-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_accountdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdb',
            old_name='Iden',
            new_name='Ide',
        ),
    ]
